Notes thomas barrett
eggheadio-projects/create-amazing-animations-with-greensock-notes pull request #1
Opened 2020-06-18 15:16 UTC by tsbarrett89

2020-06-24 17:15 UTC, laurosilvacom commented
Hey @tsbarrett89 👋🏽 great job presenting key takeaways from each lesson! Also, great intuition on creating a markdown file for each lesson. That's the format that we tend to follow.

I have a couple of suggestions that can improve the notes:

For the [README.md](https://github.com/eggheadio-projects/create-amazing-animations-with-greensock-notes/blob/master/README.md) you need to add the title of course, course illustration (you can get this from the course page), About (you can get this from instructors page on egghead), a description of the course, a "what you'll learn" section, and a table of contents with links to each markdown file.

Consider adding an [Emoji Legend](https://github.com/eggheadio-projects/build-an-app-with-the-AWS-cloud-development-kit-notes#emoji-legend-) to your notes. This will inform readers of what they can spect from each section.

An example to follow is the notes on [Build an App with the AWS Cloud Development Kit](https://github.com/eggheadio-projects/build-an-app-with-the-AWS-cloud-development-kit-notes) course. Please take a look.

You don't need to at the Contributors section; we'll add that part.

2020-06-24 17:25 UTC, laurelsilva requested changes

2020-06-24 17:25 UTC, laurosilvacom commented on 01-Setup-GreenSock-as-a-Module-with-Parcel.md
> +📹 [Video](https://egghead.io/courses/create-amazing-animations-with-greensock)
We can link to the course from the [README.md](https://github.com/eggheadio-projects/create-amazing-animations-with-greensock-notes/blob/master/README.md). Instead lets link to the lesson. 

For example: `https://egghead.io/lessons/greensock-setup-greensock-as-a-module-with-parcel`

2020-06-24 17:25 UTC, laurosilvacom commented on 01-Setup-GreenSock-as-a-Module-with-Parcel.md
> +    > yarn add -D parcel-bundler
This is great. I recommend only using the fenced code blocks -- they're easier and only they support syntax highlighting. Please refer to this [example](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting).

2020-06-24 17:25 UTC, laurosilvacom commented on 01-Setup-GreenSock-as-a-Module-with-Parcel.md
> +📹 [Video](https://egghead.io/courses/create-amazing-animations-with-greensock)
Let's do this for other lessons.

2020-06-24 17:25 UTC, laurosilvacom commented on 07-Animate-From-a-Variable-Point-with-from-and-fromTo-in-Greensock.md
> +    ```
Let's optimize to keep our markdown formatted. Code and Syntax Highlighting should not be indented. This applies for the rest of the lessons.

2020-06-24 17:25 UTC, laurosilvacom commented on 01-Setup-GreenSock-as-a-Module-with-Parcel.md
> +# Setup GreenSock As A Module With Parcel
Great job adding a title! Let's do this for the rest of the lessons.

2020-06-25 00:51 UTC, laurosilvacom commented on 01-Setup-GreenSock-as-a-Module-with-Parcel.md
> +# Setup GreenSock As A Module With Parcel
A note on the lesson slug. Let's use kebab case. 
`01-Setup-GreenSock-as-a-Module-with-Parcel.md` --> `01-setup-greensock-as-a-module-with-parcel.md`

2020-06-25 19:03 UTC, lsminter commented
Adding a `Go to Next Lesson` or `Go to Previous Lesson` buttons at the bottom of your notes page is great to have. So it would be like [Go to next lesson](github link to next lesson). Makes it very easy to navigate for people that are using the noes on github and not the notes on the lesson page.

2020-07-02 19:52 UTC, merged